/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MenuController;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JRootPane;

/**
 *
 * @author boriani
 */
public class MenuView extends javax.swing.JFrame {

    MenuController controller = new MenuController(MenuView.this);

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        getRootPane().setWindowDecorationStyle(JRootPane.PLAIN_DIALOG);
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        btClientes = new javax.swing.JButton();
        btFornecedor = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        btFuncionarios = new javax.swing.JButton();
        btVendas = new javax.swing.JButton();
        btCompras = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenuItem();
        jMenuFuncionario = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        subMenuControleDeEstoque = new javax.swing.JMenu();
        jMenuEstoque = new javax.swing.JMenuItem();
        subMenuRelatorio = new javax.swing.JMenu();
        jMenuProdutoEmFalta = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        jMenuVendas = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        jMenuCompras = new javax.swing.JMenuItem();
        menuContas = new javax.swing.JMenu();
        jMenuContasPagar = new javax.swing.JMenuItem();
        jMenuContasReceber = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Comercial de Vendas");
        setResizable(false);

        jLabel1.setText("Usuário:");

        btClientes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), null, null));
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });

        btFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fornecedor.png"))); // NOI18N
        btFornecedor.setText("Fornecedor");
        btFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), null, null));
        btFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorActionPerformed(evt);
            }
        });

        btProdutos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estoque.png"))); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), null, null));
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });

        btFuncionarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcionario.png"))); // NOI18N
        btFuncionarios.setText("Funcionários");
        btFuncionarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), null, null));
        btFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionariosActionPerformed(evt);
            }
        });

        btVendas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venda.gif"))); // NOI18N
        btVendas.setText("Vendas");
        btVendas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), null, null));
        btVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendasActionPerformed(evt);
            }
        });

        btCompras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras (1).png"))); // NOI18N
        btCompras.setText("Compras");
        btCompras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), null, null));
        btCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprasActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sairnovo.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), null, null));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        jMenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuCliente.setText("Clientes");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuCliente);

        jMenuFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuFornecedores.setText("Fornecedores");
        jMenuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFornecedoresActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuFornecedores);

        jMenuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuProdutos.setText("Produtos");
        jMenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuProdutos);

        jMenuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuFuncionario.setText("Funcionários");
        jMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(jMenuFuncionario);

        jMenuBar1.add(menuCadastro);

        menuEstoque.setText("Estoque");

        subMenuControleDeEstoque.setText("Controle de Estoque");

        jMenuEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuEstoque.setText("Estoque");
        jMenuEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstoqueActionPerformed(evt);
            }
        });
        subMenuControleDeEstoque.add(jMenuEstoque);

        menuEstoque.add(subMenuControleDeEstoque);

        subMenuRelatorio.setText("Relatórios");

        jMenuProdutoEmFalta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuProdutoEmFalta.setText("Produtos em falta");
        subMenuRelatorio.add(jMenuProdutoEmFalta);

        menuEstoque.add(subMenuRelatorio);

        jMenuBar1.add(menuEstoque);

        menuVendas.setText("Vendas");

        jMenuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuVendas.setText("Vendas");
        jMenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasActionPerformed(evt);
            }
        });
        menuVendas.add(jMenuVendas);

        jMenuBar1.add(menuVendas);

        menuCompras.setText("Compras");

        jMenuCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuCompras.setText("Efetuar Compra");
        jMenuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuComprasActionPerformed(evt);
            }
        });
        menuCompras.add(jMenuCompras);

        jMenuBar1.add(menuCompras);

        menuContas.setText("Contas");

        jMenuContasPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuContasPagar.setText("Contas a Pagar");
        jMenuContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContasPagarActionPerformed(evt);
            }
        });
        menuContas.add(jMenuContasPagar);

        jMenuContasReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuContasReceber.setText("Contas a Receber");
        jMenuContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContasReceberActionPerformed(evt);
            }
        });
        menuContas.add(jMenuContasReceber);

        jMenuBar1.add(menuContas);

        menuSistema.setText("Sistema");

        jMenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuSobre.setText("Sobre");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });
        menuSistema.add(jMenuSobre);

        jMenuLogout.setText("Logout");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        menuSistema.add(jMenuLogout);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        menuSistema.add(jMenuSair);

        jMenuBar1.add(menuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btClientes.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionariosActionPerformed
        controller.acaoFuncionarios();
    }//GEN-LAST:event_btFuncionariosActionPerformed

    private void btComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprasActionPerformed
        controller.acaoCompras();
    }//GEN-LAST:event_btComprasActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        controller.acaoSair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        controller.acaoClientes();
    }//GEN-LAST:event_btClientesActionPerformed

    private void btVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendasActionPerformed
        controller.acaoVendas();
    }//GEN-LAST:event_btVendasActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        controller.acaoProdutos();
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorActionPerformed
        controller.acaoFornecedores();
    }//GEN-LAST:event_btFornecedorActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        controller.acaoClientes();
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFornecedoresActionPerformed
        controller.acaoFornecedores();
    }//GEN-LAST:event_jMenuFornecedoresActionPerformed

    private void jMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuncionarioActionPerformed
        controller.acaoFuncionarios();
    }//GEN-LAST:event_jMenuFuncionarioActionPerformed

    private void jMenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutosActionPerformed
        controller.acaoProdutos();
    }//GEN-LAST:event_jMenuProdutosActionPerformed

    private void jMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasActionPerformed
        controller.acaoVendas();
    }//GEN-LAST:event_jMenuVendasActionPerformed

    private void jMenuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComprasActionPerformed
        controller.acaoCompras();
    }//GEN-LAST:event_jMenuComprasActionPerformed

    private void jMenuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstoqueActionPerformed
        controller.acaoJMenuEstoque();
    }//GEN-LAST:event_jMenuEstoqueActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed
        controller.acaoJMenuSobre();
    }//GEN-LAST:event_jMenuSobreActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        controller.acaoSair();
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void jMenuContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContasPagarActionPerformed
        controller.acaoJMenuContasPagar();
    }//GEN-LAST:event_jMenuContasPagarActionPerformed

    private void jMenuContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContasReceberActionPerformed
        controller.acaoJMenuContasReceber();
    }//GEN-LAST:event_jMenuContasReceberActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        dispose();

        controller.acaoJMenuLogout();
    }//GEN-LAST:event_jMenuLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btCompras;
    private javax.swing.JButton btFornecedor;
    private javax.swing.JButton btFuncionarios;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVendas;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuCompras;
    private javax.swing.JMenuItem jMenuContasPagar;
    private javax.swing.JMenuItem jMenuContasReceber;
    private javax.swing.JMenuItem jMenuEstoque;
    private javax.swing.JMenuItem jMenuFornecedores;
    private javax.swing.JMenuItem jMenuFuncionario;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenuItem jMenuProdutoEmFalta;
    private javax.swing.JMenuItem jMenuProdutos;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSobre;
    private javax.swing.JMenuItem jMenuVendas;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuContas;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenu subMenuControleDeEstoque;
    private javax.swing.JMenu subMenuRelatorio;
    // End of variables declaration//GEN-END:variables

    public JButton getBtClientes() {
        return btClientes;
    }

    public void setBtClientes(JButton btClientes) {
        this.btClientes = btClientes;
    }

    public JButton getBtCompras() {
        return btCompras;
    }

    public void setBtCompras(JButton btCompras) {
        this.btCompras = btCompras;
    }

    public JButton getBtFornecedor() {
        return btFornecedor;
    }

    public void setBtFornecedor(JButton btFornecedor) {
        this.btFornecedor = btFornecedor;
    }

    public JButton getBtFuncionarios() {
        return btFuncionarios;
    }

    public void setBtFuncionarios(JButton btFuncionarios) {
        this.btFuncionarios = btFuncionarios;
    }

    public JButton getBtProdutos() {
        return btProdutos;
    }

    public void setBtProdutos(JButton btProdutos) {
        this.btProdutos = btProdutos;
    }

    public JButton getBtSair() {
        return btSair;
    }

    public void setBtSair(JButton btSair) {
        this.btSair = btSair;
    }

    public JButton getBtVendas() {
        return btVendas;
    }

    public void setBtVendas(JButton btVendas) {
        this.btVendas = btVendas;
    }

    public JMenu getMenuCadastro() {
        return menuCadastro;
    }

    public void setMenuCadastro(JMenu menuCadastro) {
        this.menuCadastro = menuCadastro;
    }

    public JMenu getMenuCompras() {
        return menuCompras;
    }

    public void setMenuCompras(JMenu menuCompras) {
        this.menuCompras = menuCompras;
    }

    public JMenu getMenuContas() {
        return menuContas;
    }

    public void setMenuContas(JMenu menuContas) {
        this.menuContas = menuContas;
    }

    public JMenu getMenuEstoque() {
        return menuEstoque;
    }

    public void setMenuEstoque(JMenu menuEstoque) {
        this.menuEstoque = menuEstoque;
    }

    public JMenu getMenuSistema() {
        return menuSistema;
    }

    public void setMenuSistema(JMenu menuSistema) {
        this.menuSistema = menuSistema;
    }

    public JMenu getMenuVendas() {
        return menuVendas;
    }

    public void setMenuVendas(JMenu menuVendas) {
        this.menuVendas = menuVendas;
    }

    public JMenuItem getjMenuCliente() {
        return jMenuCliente;
    }

    public void setjMenuCliente(JMenuItem jMenuCliente) {
        this.jMenuCliente = jMenuCliente;
    }

    public JMenuItem getjMenuCompras() {
        return jMenuCompras;
    }

    public void setjMenuCompras(JMenuItem jMenuCompras) {
        this.jMenuCompras = jMenuCompras;
    }

    public JMenuItem getjMenuContasPagar() {
        return jMenuContasPagar;
    }

    public void setjMenuContasPagar(JMenuItem jMenuContasPagar) {
        this.jMenuContasPagar = jMenuContasPagar;
    }

    public JMenuItem getjMenuContasReceber() {
        return jMenuContasReceber;
    }

    public void setjMenuContasReceber(JMenuItem jMenuContasReceber) {
        this.jMenuContasReceber = jMenuContasReceber;
    }

    public JMenuItem getjMenuEstoque() {
        return jMenuEstoque;
    }

    public void setjMenuEstoque(JMenuItem jMenuEstoque) {
        this.jMenuEstoque = jMenuEstoque;
    }

    public JMenuItem getjMenuFornecedores() {
        return jMenuFornecedores;
    }

    public void setjMenuFornecedores(JMenuItem jMenuFornecedores) {
        this.jMenuFornecedores = jMenuFornecedores;
    }

    public JMenuItem getjMenuFuncionario() {
        return jMenuFuncionario;
    }

    public void setjMenuFuncionario(JMenuItem jMenuFuncionario) {
        this.jMenuFuncionario = jMenuFuncionario;
    }

    public JMenuItem getjMenuLogout() {
        return jMenuLogout;
    }

    public void setjMenuLogout(JMenuItem jMenuLogout) {
        this.jMenuLogout = jMenuLogout;
    }

    public JMenuItem getjMenuProdutoEmFalta() {
        return jMenuProdutoEmFalta;
    }

    public void setjMenuProdutoEmFalta(JMenuItem jMenuProdutoEmFalta) {
        this.jMenuProdutoEmFalta = jMenuProdutoEmFalta;
    }

    public JMenuItem getjMenuProdutos() {
        return jMenuProdutos;
    }

    public void setjMenuProdutos(JMenuItem jMenuProdutos) {
        this.jMenuProdutos = jMenuProdutos;
    }

    public JMenuItem getjMenuSair() {
        return jMenuSair;
    }

    public void setjMenuSair(JMenuItem jMenuSair) {
        this.jMenuSair = jMenuSair;
    }

    public JMenuItem getjMenuSobre() {
        return jMenuSobre;
    }

    public void setjMenuSobre(JMenuItem jMenuSobre) {
        this.jMenuSobre = jMenuSobre;
    }

    public JMenuItem getjMenuVendas() {
        return jMenuVendas;
    }

    public void setjMenuVendas(JMenuItem jMenuVendas) {
        this.jMenuVendas = jMenuVendas;
    }

}
